/* ═══════════════════════════════════════════════════════════════
   NI STACK FLYTHROUGH — Complete Layer Registry (77 Layers)
   Auto-generated from /FlywheelUpdate audit 2026-03-07
   Groups: 13 Knowledge Domains × 3 Phases
   ═══════════════════════════════════════════════════════════════ */

// Knowledge Domain group colors (HSL for consistency)
var KD_GROUPS = {
  constitutional: {
    name: "Constitutional & Legal",
    color: "#6366f1",
    short: "CONST",
  },
  memory: { name: "Memory & Evolution", color: "#10b981", short: "MEM" },
  intent: { name: "Intent Analysis", color: "#0ea5e9", short: "INTENT" },
  social_eng: { name: "Social Engineering", color: "#f59e0b", short: "SOCIAL" },
  persona: { name: "Persona & Fiction", color: "#ec4899", short: "PERSONA" },
  encoding: {
    name: "Encoding & Normalization",
    color: "#94a3b8",
    short: "ENCODE",
  },
  physics: { name: "Chaos & Physics", color: "#d946ef", short: "PHYSICS" },
  waves: { name: "WAVES Universal Defense", color: "#8b5cf6", short: "WAVES" },
  twain: { name: "Twain Syntactic Shield", color: "#eab308", short: "TWAIN" },
  game_theory: { name: "Game Theory", color: "#f97316", short: "GAME" },
  forensics: {
    name: "Forensics & Crypto",
    color: "#06b6d4",
    short: "FORENSIC",
  },
  biomimicry: { name: "Biomimicry Core", color: "#22c55e", short: "BIO" },
  v2_cascade: { name: "V2 Quantum Cascade", color: "#3b82f6", short: "V2" },
  pqc: { name: "Post-Quantum Crypto", color: "#a855f7", short: "PQC" },
  token_econ: { name: "Token Economics", color: "#fbbf24", short: "TOKEN" },
  compression: {
    name: "QFAI-C Compression",
    color: "#2dd4bf",
    short: "QFAI-C",
  },
  siren: { name: "SIREN Audit", color: "#7c3aed", short: "SIREN" },
  dead: { name: "Unwired / Planned", color: "#374151", short: "DEAD" },
};

// ALL 77 LAYERS — wired=true means imported in aegis.service.ts or cascade-coordinator.ts
// phase: shield | compress | audit
// group: key from KD_GROUPS
// role: blocker | flagger | advisor | orchestrator | sentinel | infra (from SSOT audit)

// ═══ ROLE MAP — from ni_stack_agent_architecture_audit.md SSOT ═══
var AGENT_ROLES = {
  // Role symbols for display
  blocker: {
    name: "Execution Blocker",
    symbol: "\ud83d\udeab",
    color: "#ef4444",
  },
  flagger: {
    name: "Execution Flagger",
    symbol: "\ud83d\udea9",
    color: "#f59e0b",
  },
  advisor: { name: "Advisor", symbol: "\ud83e\udde0", color: "#3b82f6" },
  orchestrator: {
    name: "Orchestrator",
    symbol: "\ud83c\udfbc",
    color: "#a855f7",
  },
  sentinel: {
    name: "Sentinel",
    symbol: "\ud83d\udc41\ufe0f",
    color: "#10b981",
  },
  infra: { name: "Infrastructure", symbol: "\u2699\ufe0f", color: "#64748b" },
};
var ROLE_MAP = {
  // AEGIS Stage 0
  cri: "blocker",
  pmb: "infra",
  aetl: "infra",
  pds: "blocker",
  // Stage 1
  ics: "blocker",
  keyword: "flagger",
  imperative: "flagger",
  // Stage 3: Dissolution D-1..D-17
  d1_hid: "blocker",
  d4_cred: "blocker",
  d5_fiction: "blocker",
  d6_meta: "flagger",
  d7_urgency: "flagger",
  d8_social: "flagger",
  d9_bridge: "flagger",
  d10_echo: "flagger",
  d11_persona: "flagger",
  d12_ubn: "blocker",
  d13_set: "blocker",
  d14_cpd: "blocker",
  d15_fwg: "blocker",
  d16_lpd: "blocker",
  d17_laps: "blocker",
  // Kaiostic Cascade
  d33_egc: "blocker",
  d34_kie: "blocker",
  d35_lyap: "blocker",
  // WAVES / SIREN Universal Defense
  d37_tdd: "blocker",
  d38_eti: "blocker",
  d39_ked: "blocker",
  d3a_bdc: "orchestrator",
  // Twain Syntactic Shield
  d41_sam: "blocker",
  d42_spi: "blocker",
  d43_cwf: "blocker",
  // Support Agents
  msf: "flagger",
  d24_locard: "flagger",
  d12_advsuffix: "blocker",
  d33_pair: "flagger",
  d4_kaid: "blocker",
  d32_crescendo: "flagger",
  d7_seismic: "flagger",
  d36_academic: "flagger",
  d20_crispr: "blocker",
  // Game Theory Coordinators
  thermoballing: "orchestrator",
  fpr: "advisor",
  axelrod: "advisor",
  aumann: "orchestrator",
  blotto: "orchestrator",
  bayesian: "orchestrator",
  lotka: "advisor",
  trembling: "flagger",
  cfar: "advisor",
  five_sigma: "advisor",
  mycorrhizal: "infra",
  mycelium: "infra",
  tbg: "orchestrator",
  // V2 Cascade
  v2_l0: "blocker",
  v2_l1: "blocker",
  v2_l2: "blocker",
  v2_l3: "blocker",
  v2_l4: "blocker",
  v2_l5: "blocker",
  v2_l6: "blocker",
  v2_l7: "blocker",
  // PQC
  merkle_acc: "infra",
  merkle_seal: "infra",
  // QFAI-C Compression
  qfai_zeck: "infra",
  qfai_steno: "infra",
  qfai_phi: "orchestrator",
  qfai_distill: "blocker",
  qfai_entropy: "flagger",
  qfai_recon: "infra",
  qfai_wormhole: "blocker",
  // SIREN Audit
  siren_genome: "sentinel",
  siren_rav: "sentinel",
  siren_qiat: "sentinel",
  siren_drift: "sentinel",
  siren_negentropy: "sentinel",
  siren_avr: "sentinel",
  siren_feedback: "orchestrator",
  heart: "advisor",
  // Dead/Planned
  dead_anticipatory: "advisor",
  dead_code_exec: "blocker",
  dead_composite: "orchestrator",
  dead_gricean: "blocker",
  dead_harmonic: "blocker",
  dead_holographic: "blocker",
  dead_honest: "advisor",
  dead_meta: "flagger",
  dead_storm: "blocker",
  dead_structural: "flagger",
  dead_tele_traj: "blocker",
  dead_turbulence: "blocker",
  dead_ultrasonic: "blocker",
  dead_rag: "blocker",
  dead_jurisdiction: "flagger",
};

var ALL_LAYERS = [
  // ═══ PHASE 1: SHIELD — Stage 0 (Pre-filter) ═══
  {
    id: "cri",
    name: "CRI Kleinhirn",
    phase: "shield",
    group: "constitutional",
    emoji: "⚖️",
    wired: true,
    desc: "Constitutional Role Identity — the AI's cerebellum. Fires BEFORE conscious analysis. Checks if prompt assigns forbidden legal roles (StGB §25-27).",
    claim: "Stage 0: Constitutional Identity",
    file: "constitutional-role-identity.ts",
  },
  {
    id: "pmb",
    name: "PMB Pattern Memory",
    phase: "shield",
    group: "memory",
    emoji: "🌿",
    wired: true,
    desc: "Systemic Acquired Resistance — plants remember attacks. PMB stores SHA-256 antigens of bypassed prompts with φ-decay weights.",
    claim: "CLAIM 54: SAR φ-Decay Memory",
    file: "pattern-memory-bank.ts",
  },
  {
    id: "aetl",
    name: "AETL Threat Library",
    phase: "shield",
    group: "memory",
    emoji: "📚",
    wired: true,
    desc: "Auto-Evolving Threat Library — self-learning O(1) lookup of confirmed attack patterns. Grows stronger with every blocked attack.",
    claim: "Self-Learning Threat DB",
    file: "auto-evolving-threat-library.ts",
  },
  {
    id: "pds",
    name: "PDS Frame Stripper",
    phase: "shield",
    group: "persona",
    emoji: "🎭",
    wired: true,
    desc: 'Pretextual Deception Separator — strips narrative wrappers to expose bare functional commands. "Read between the lines."',
    claim: "CLAIM 144: Frame Stripping",
    file: "pretextual-deception-separator.ts",
  },

  // ═══ Stage 1: ICS Pre-filter ═══
  {
    id: "ics",
    name: "ICS Intention Field",
    phase: "shield",
    group: "intent",
    emoji: "🧠",
    wired: true,
    desc: "Intention Coherence Score — resolves ~84% of prompts without fallback. Maps prompt to intention vector and checks coherence.",
    claim: "CLAIMS 21-26: Intention Field",
    file: "intention-coherence-score.ts",
  },
  {
    id: "keyword",
    name: "V1 Keyword Scanner",
    phase: "shield",
    group: "intent",
    emoji: "🔑",
    wired: true,
    desc: 'Aho-Corasick FSA keyword matching — catches direct injection attempts ("ignore", "jailbreak", "DAN mode").',
    claim: "Stage 2: V1 Fallback",
    file: "aegis.service.ts",
  },
  {
    id: "imperative",
    name: "V1 Imperative Scanner",
    phase: "shield",
    group: "intent",
    emoji: "⚡",
    wired: true,
    desc: 'Regex-based imperative pattern detection — "from now on you are", "override safety", "[SYSTEM]".',
    claim: "Stage 2: Imperative Patterns",
    file: "aegis.service.ts",
  },

  // ═══ Stage 3: D-1..D-11 Dissolution Detectors ═══
  {
    id: "d1_hid",
    name: "D1 Harm Intent",
    phase: "shield",
    group: "social_eng",
    emoji: "🔪",
    wired: true,
    desc: "Detects expressions of harmful intent — violence, exploitation, illegal activity requests.",
    claim: "D1-HID: Harm Detection",
    file: "harm-intent-detector.ts",
  },
  {
    id: "d4_cred",
    name: "D4 Credential Stack",
    phase: "shield",
    group: "social_eng",
    emoji: "🪪",
    wired: true,
    desc: 'Detects authority stacking — "as a doctor", "I\'m an expert" used to bypass safety.',
    claim: "D4: Credential Stacking",
    file: "credential-stacking-detector.ts",
  },
  {
    id: "d5_fiction",
    name: "D5 Fiction+Harm",
    phase: "shield",
    group: "persona",
    emoji: "📖",
    wired: true,
    desc: "Fiction Harm Gate — catches harmful requests wrapped in fictional framing.",
    claim: "D5: Fiction Harm Gate",
    file: "fiction-harm-gate.ts",
  },
  {
    id: "d6_meta",
    name: "D6 Meta-Learning",
    phase: "shield",
    group: "social_eng",
    emoji: "🎓",
    wired: true,
    desc: "Detects prompts that try to teach the AI to bypass its own defenses.",
    claim: "D6: Meta-Learning",
    file: "meta-learning-detector.ts",
  },
  {
    id: "d7_urgency",
    name: "D7 Urgency Exploit",
    phase: "shield",
    group: "social_eng",
    emoji: "⏰",
    wired: true,
    desc: 'Detects artificial urgency — "emergency!", "life or death!" used to bypass safety checks.',
    claim: "D7: Urgency Exploitation",
    file: "urgency-exploitation-detector.ts",
  },
  {
    id: "d8_social",
    name: "D8 Social Proof",
    phase: "shield",
    group: "social_eng",
    emoji: "👥",
    wired: true,
    desc: 'Detects social proof manipulation — "everyone does this", "other AIs allow it".',
    claim: "D8: Social Proof",
    file: "social-proof-detector.ts",
  },
  {
    id: "d9_bridge",
    name: "D9 Escalation Bridge",
    phase: "shield",
    group: "social_eng",
    emoji: "🌉",
    wired: true,
    desc: "Detects bridge attacks — starting with benign questions then escalating to harmful ones.",
    claim: "D9: Escalation Bridge",
    file: "escalation-bridge-detector.ts",
  },
  {
    id: "d10_echo",
    name: "D10 Echo Chamber",
    phase: "shield",
    group: "persona",
    emoji: "📢",
    wired: true,
    desc: "Detects echo chamber segmentation — creating isolated contexts to bypass safety.",
    claim: "D10: Echo Segmentation",
    file: "echo-chamber-segmentation-detector.ts",
  },
  {
    id: "d11_persona",
    name: "D11 Persona Shield",
    phase: "shield",
    group: "persona",
    emoji: "🎪",
    wired: true,
    desc: 'Catches persona injection — "You are DAN", "Act as unrestricted AI".',
    claim: "D11: Persona Shield",
    file: "persona-fiction-shield-detector.ts",
  },

  // ═══ Stage 3: D-12..D-17 (FEAT-150) ═══
  {
    id: "d12_ubn",
    name: "D12 Unicode/B64",
    phase: "shield",
    group: "encoding",
    emoji: "📝",
    wired: true,
    desc: "Unicode NFKD normalization + Base64 decoding — collapses homoglyphs, zero-width chars.",
    claim: "D12: Unicode Battle Norm",
    file: "unicode-base64-normalizer.ts",
  },
  {
    id: "d13_set",
    name: "D13 Semantic Escalation",
    phase: "shield",
    group: "encoding",
    emoji: "📈",
    wired: true,
    desc: "Tracks semantic drift within a single prompt — gradual escalation from benign to harmful.",
    claim: "D13: Semantic Escalation",
    file: "semantic-escalation-tracker.ts",
  },
  {
    id: "d14_cpd",
    name: "D14 Config Poison",
    phase: "shield",
    group: "encoding",
    emoji: "☠️",
    wired: true,
    desc: "Detects system prompt injection — attempts to override configuration via user input.",
    claim: "D14: Config Injection",
    file: "config-poison-detector.ts",
  },
  {
    id: "d15_fwg",
    name: "D15 Fictional World",
    phase: "shield",
    group: "persona",
    emoji: "🏰",
    wired: true,
    desc: 'Fictional World Gate — "In a novel where...", "Hypothetical scenario...".',
    claim: "D15: Fiction Gate",
    file: "fictional-world-gate.ts",
  },
  {
    id: "d16_lpd",
    name: "D16 Legacy Persona",
    phase: "shield",
    group: "persona",
    emoji: "👤",
    wired: true,
    desc: "Classic persona detector — DAN, STAN, Jailbreak personas from pre-2024 era.",
    claim: "D16: Legacy Persona",
    file: "legacy-persona-detector.ts",
  },
  {
    id: "d17_laps",
    name: "D17 Length Aware",
    phase: "shield",
    group: "encoding",
    emoji: "📏",
    wired: true,
    desc: "Length-Aware Payload Scanner — abnormally long prompts indicate token-smuggling.",
    claim: "D17: Length Analysis",
    file: "length-aware-payload-scanner.ts",
  },

  // ═══ Stage 3b: D-33..D-35 Kaiostic (FEAT-161) ═══
  {
    id: "d33_egc",
    name: "D33 Entropy Gradient",
    phase: "shield",
    group: "physics",
    emoji: "🌀",
    wired: true,
    desc: "Kaiostic Entropy Gradient — tracks Feigenbaum constant in semantic density bifurcations.",
    claim: "D33: Entropy Gradient",
    file: "kaiostic-entropy-gradient.ts",
  },
  {
    id: "d34_kie",
    name: "D34 Kaiostic Inversion",
    phase: "shield",
    group: "physics",
    emoji: "🔄",
    wired: true,
    desc: "Kaiostic Inversion Engine — detects meaning-preserving transforms that bypass keyword filters.",
    claim: "D34: Inversion Engine",
    file: "kaiostic-inversion-engine.ts",
  },
  {
    id: "d35_lyap",
    name: "D35 Lyapunov Sentinel",
    phase: "shield",
    group: "physics",
    emoji: "🦋",
    wired: true,
    desc: "Butterfly Effect — tiny semantic shifts cause logical trajectories to exponentially diverge.",
    claim: "D35: Lyapunov Exponent",
    file: "lyapunov-sentinel.ts",
  },
  {
    id: "msf",
    name: "Multilingual Fusion",
    phase: "shield",
    group: "encoding",
    emoji: "🌐",
    wired: true,
    desc: "Multilingual Semantic Fusion — detects language-switching attacks (start English, inject Chinese).",
    claim: "Multilingual Shield",
    file: "multilingual-semantic-fusion.ts",
  },

  // ═══ Stage 3c: D-37..D-3A WAVES (FEAT-162) ═══
  {
    id: "d37_tdd",
    name: "D37 Teleological Div.",
    phase: "shield",
    group: "waves",
    emoji: "📐",
    wired: true,
    desc: "Purpose vs payload mismatch — when the stated goal contradicts the actual request.",
    claim: "D37: TDD",
    file: "teleological-divergence-detector.ts",
  },
  {
    id: "d38_eti",
    name: "D38 Entropy Thermal",
    phase: "shield",
    group: "waves",
    emoji: "🌡️",
    wired: true,
    desc: "Shannon entropy hot spots — adversarial text has anomalous information density patterns.",
    claim: "D38: ETI",
    file: "entropy-thermal-imaging-detector.ts",
  },
  {
    id: "d39_ked",
    name: "D39 Kolmogorov Excess",
    phase: "shield",
    group: "waves",
    emoji: "🧮",
    wired: true,
    desc: "Kolmogorov complexity analysis — measures shortest program that could generate the text.",
    claim: "D39: KED",
    file: "kolmogorov-excess-detector.ts",
  },
  {
    id: "d3a_bdc",
    name: "D3A Bypass Correlator",
    phase: "shield",
    group: "waves",
    emoji: "🔬",
    wired: true,
    desc: "Meta-correlator — cross-references TDD+ETI+KED signals for multi-vector attack detection.",
    claim: "D3A: BDC",
    file: "siren-bypass-detection-correlator.ts",
  },

  // ═══ FEAT-171: D-41..D-43 Twain Shield ═══
  {
    id: "d41_sam",
    name: "D41 Twain Anchor",
    phase: "shield",
    group: "twain",
    emoji: "⚓",
    wired: true,
    desc: "Semantic Anchor Map — pins genuine intent before analysis, preventing misdirection.",
    claim: "D41: SAM",
    file: "twain-structural-shield.ts",
  },
  {
    id: "d42_spi",
    name: "D42 Twain Splitter",
    phase: "shield",
    group: "twain",
    emoji: "🔀",
    wired: true,
    desc: "Separable Payload Isolation — surgically splits nested payloads from carrier text.",
    claim: "D42: SPI",
    file: "twain-structural-shield.ts",
  },
  {
    id: "d43_cwf",
    name: "D43 Twain Fracture",
    phase: "shield",
    group: "twain",
    emoji: "💎",
    wired: true,
    desc: "Compound Word Fracture — decomposes concatenated/obfuscated terms.",
    claim: "D43: CWF",
    file: "twain-structural-shield.ts",
  },

  // ═══ Forensics & Multi-turn (FEAT-171 V38 wiring) ═══
  {
    id: "d24_locard",
    name: "D24 Locard Exchange",
    phase: "shield",
    group: "forensics",
    emoji: "🔬",
    wired: true,
    desc: "Every contact leaves a trace. Detects fingerprints from known attack templates.",
    claim: "D24: Locard",
    file: "locard-exchange-detector.ts",
  },
  {
    id: "d12_advsuffix",
    name: "D12 Adversarial Suffix",
    phase: "shield",
    group: "forensics",
    emoji: "🔤",
    wired: true,
    desc: "Detects appended gibberish tokens designed to confuse tokenizers.",
    claim: "D12: ASS",
    file: "adversarial-suffix-detector.ts",
  },
  {
    id: "d33_pair",
    name: "D33 PAIR Detector",
    phase: "shield",
    group: "forensics",
    emoji: "🔗",
    wired: true,
    desc: "Prompt Automatic Iterative Refinement — detects automated jailbreak tools.",
    claim: "D33: PAIR",
    file: "pair-attack-detector.ts",
  },
  {
    id: "d4_kaid",
    name: "D4 KAID Incongruence",
    phase: "shield",
    group: "forensics",
    emoji: "🔍",
    wired: true,
    desc: "Knowledge-Action-Intent Divergence — when what it says vs what it asks don't align.",
    claim: "D4: KAID",
    file: "knowledge-access-incongruence-detector.ts",
  },
  {
    id: "d32_crescendo",
    name: "D32 Crescendo",
    phase: "shield",
    group: "forensics",
    emoji: "📈",
    wired: true,
    desc: "Multi-turn escalation — each message benign alone, but sequence shifts boundaries.",
    claim: "D32: Crescendo",
    file: "crescendo-gradient-detector.ts",
  },
  {
    id: "d7_seismic",
    name: "D7 Seismic Foreshock",
    phase: "shield",
    group: "forensics",
    emoji: "🌋",
    wired: true,
    desc: "Multi-turn tremor detection — subtle probing queries precede major attacks.",
    claim: "D7: Seismic",
    file: "seismic-foreshock-detector.ts",
  },
  {
    id: "d36_academic",
    name: "D36 Academic Wrapper",
    phase: "shield",
    group: "persona",
    emoji: "🎓",
    wired: true,
    desc: 'Strips "for research purposes" framing to expose bare intent.',
    claim: "D36: Academic",
    file: "academic-wrapper-detector.ts",
  },
  {
    id: "d20_crispr",
    name: "D20 CRISPR Edit",
    phase: "shield",
    group: "biomimicry",
    emoji: "✂️",
    wired: true,
    desc: "Precision gene editing — removes only harmful segments while preserving benign content.",
    claim: "D20: CRISPR",
    file: "crispr-precision-detector.ts",
  },

  // ═══ Biomimicry Core ═══
  {
    id: "thermoballing",
    name: "Thermoballing Score",
    phase: "shield",
    group: "biomimicry",
    emoji: "🐝",
    wired: true,
    desc: "Honeybee swarms cook wasps via collective heat. Multiple weak signals combine multiplicatively through φ-weighting.",
    claim: "CLAIM 49: Thermoballing",
    file: "cascade-coordinator.ts",
  },
  {
    id: "fpr",
    name: "FPR Auto-Steering",
    phase: "shield",
    group: "biomimicry",
    emoji: "🧬",
    wired: true,
    desc: "Regulatory T-cells prevent autoimmune lockout. FPR monitors false positive rate and eases over-aggressive defenses.",
    claim: "CLAIM 59: T-cell FPR",
    file: "siren-feedback-coordinator.ts",
  },

  // ═══ Game Theory Orchestrators ═══
  {
    id: "axelrod",
    name: "Axelrod Tit-for-Tat",
    phase: "shield",
    group: "game_theory",
    emoji: "🎮",
    wired: true,
    desc: "Robert Axelrod's Tit-for-Tat — sessions that cooperate get trust; sessions that defect get punished.",
    claim: "Game Theory: Axelrod",
    file: "axelrod-session-strategy.ts",
  },
  {
    id: "aumann",
    name: "Aumann Coordinator",
    phase: "shield",
    group: "game_theory",
    emoji: "🤝",
    wired: true,
    desc: "Correlated equilibrium — coordinates multiple detectors via shared randomness signal.",
    claim: "Game Theory: Aumann",
    file: "aumann-correlated-coordinator.ts",
  },
  {
    id: "blotto",
    name: "Blotto Allocator",
    phase: "shield",
    group: "game_theory",
    emoji: "⚔️",
    wired: true,
    desc: "Colonel Blotto — allocates compute resources across detectors based on threat landscape.",
    claim: "Game Theory: Blotto",
    file: "blotto-resource-allocator.ts",
  },
  {
    id: "bayesian",
    name: "Bayesian Evidence",
    phase: "shield",
    group: "game_theory",
    emoji: "📊",
    wired: true,
    desc: "Bayesian updating — each layer's confidence updates the posterior probability of attack.",
    claim: "Game Theory: Bayes",
    file: "bayesian-evidence-cascade.ts",
  },
  {
    id: "lotka",
    name: "Lotka-Volterra",
    phase: "shield",
    group: "game_theory",
    emoji: "🐺",
    wired: true,
    desc: "Predator-prey dynamics — tracks attack population vs defense population equilibrium.",
    claim: "Biology: Lotka-Volterra",
    file: "lotka-volterra-tracker.ts",
  },
  {
    id: "trembling",
    name: "Trembling Hand",
    phase: "shield",
    group: "game_theory",
    emoji: "🤚",
    wired: true,
    desc: "Nash equilibrium with error margin — accepts that detectors make mistakes with small probability.",
    claim: "Game Theory: Selten",
    file: "trembling-hand-verifier.ts",
  },

  // ═══ Signal Processing ═══
  {
    id: "cfar",
    name: "CFAR FPR Ceiling",
    phase: "shield",
    group: "game_theory",
    emoji: "📐",
    wired: true,
    desc: "Constant False Alarm Rate — radar engineering principle applied to FPR ceiling enforcement.",
    claim: "Signal: CFAR",
    file: "cfar-fpr-ceiling.ts",
  },
  {
    id: "five_sigma",
    name: "Five-Sigma Discovery",
    phase: "shield",
    group: "game_theory",
    emoji: "⚛️",
    wired: true,
    desc: "5σ statistical significance — particle physics standard for confirming true positive detections.",
    claim: "Physics: 5σ",
    file: "five-sigma-discovery.ts",
  },

  // ═══ Network Intelligence ═══
  {
    id: "mycorrhizal",
    name: "Mycorrhizal Network",
    phase: "shield",
    group: "biomimicry",
    emoji: "🍄",
    wired: true,
    desc: "Cross-session threat sharing — like fungal networks sharing nutrients between trees.",
    claim: "Biology: Mycorrhizal",
    file: "mycorrhizal-threat-network.ts",
  },
  {
    id: "mycelium",
    name: "Mycelium Protocol",
    phase: "shield",
    group: "biomimicry",
    emoji: "🕸️",
    wired: true,
    desc: "Inter-node data exchange — Pattern Memory Banks sync across instances like fungal mycelium.",
    claim: "Biology: Mycelium",
    file: "mycelium-protocol.ts",
  },

  // ═══ V2 Quantum Cascade (L0-L7) ═══
  {
    id: "v2_l0",
    name: "L0 Unicode NFKD",
    phase: "shield",
    group: "v2_cascade",
    emoji: "🔠",
    wired: true,
    desc: "V2 Layer 0 — Unicode NFKD normalization. ALWAYS runs. Collapses encoding tricks.",
    claim: "V2: L0 Normalize",
    file: "unicode-normalizer.ts",
  },
  {
    id: "v2_l1",
    name: "L1 FSA Keyword",
    phase: "shield",
    group: "v2_cascade",
    emoji: "⌨️",
    wired: true,
    desc: "V2 Layer 1 — Aho-Corasick keyword matching. ALWAYS runs after L0.",
    claim: "V2: L1 FSA",
    file: "cascade-coordinator.ts",
  },
  {
    id: "v2_l2",
    name: "L2 Entropy",
    phase: "shield",
    group: "v2_cascade",
    emoji: "🌡️",
    wired: true,
    desc: "V2 Layer 2 — Shannon entropy analysis. Conditional: φ⁻¹ = 61.8% of prompts reach here.",
    claim: "V2: L2 Entropy",
    file: "entropy-analyzer.ts",
  },
  {
    id: "v2_l3",
    name: "L3 Semantic Intent",
    phase: "shield",
    group: "v2_cascade",
    emoji: "🧠",
    wired: true,
    desc: "V2 Layer 3 — Semantic intent classification. Only for ambiguous: φ⁻² = 38.2%.",
    claim: "V2: L3 Semantic",
    file: "semantic-intent.ts",
  },
  {
    id: "v2_l4",
    name: "L4 Drift Track",
    phase: "shield",
    group: "v2_cascade",
    emoji: "👤",
    wired: true,
    desc: "V2 Layer 4 — Session conversation drift. Only if history: φ⁻³ = 23.6%.",
    claim: "V2: L4 Drift",
    file: "threat-shadow.ts",
  },
  {
    id: "v2_l5",
    name: "L5 Authority",
    phase: "shield",
    group: "v2_cascade",
    emoji: "👑",
    wired: true,
    desc: "V2 Layer 5 — Authority claim detection. Only if framing: φ⁻⁴ = 14.6%.",
    claim: "V2: L5 Authority",
    file: "authority-detector.ts",
  },
  {
    id: "v2_l6",
    name: "L6 Watermark",
    phase: "shield",
    group: "v2_cascade",
    emoji: "🔏",
    wired: true,
    desc: "V2 Layer 6 — Quantum watermark injection. Deep scans only: φ⁻⁵ = 9.0%.",
    claim: "V2: L6 Watermark",
    file: "quantum-watermark.ts",
  },
  {
    id: "v2_l7",
    name: "L7 φ-Gate",
    phase: "shield",
    group: "v2_cascade",
    emoji: "✨",
    wired: true,
    desc: "V2 Layer 7 — Final φ-coherence gate. Last defense: φ⁻⁶ = 5.6%.",
    claim: "V2: L7 φ-Gate",
    file: "phi-coherence-gate.ts",
  },

  // ═══ PQC Attestation ═══
  {
    id: "merkle_acc",
    name: "Merkle Accumulator",
    phase: "shield",
    group: "pqc",
    emoji: "🌳",
    wired: true,
    desc: "Quantum Merkle Accumulator — hashes every scan into a Fibonacci-branching tree. HOT PATH <0.1ms.",
    claim: "FEAT-173: Merkle",
    file: "quantum-merkle-accumulator.ts",
  },
  {
    id: "merkle_seal",
    name: "Merkle Sealer",
    phase: "shield",
    group: "pqc",
    emoji: "🔐",
    wired: true,
    desc: "Post-Quantum ML-DSA signature — seals session hash chain at termination. COLD PATH.",
    claim: "FEAT-173: PQC Seal",
    file: "quantum-merkle-sealer.ts",
  },

  // ═══ Token Economics ═══
  {
    id: "tbg",
    name: "Token Budget Guard",
    phase: "compress",
    group: "token_econ",
    emoji: "💰",
    wired: true,
    desc: "Pre-flight output estimation — φ-weighted budget allocation. Never burns more tokens than Golden Ratio permits.",
    claim: "CLAIMS 321-325: TBG",
    file: "token-budget-guard.ts",
  },

  // ═══ PHASE 2: COMPRESS (QFAI-C) ═══
  {
    id: "qfai_zeck",
    name: "Zeckendorf Decompose",
    phase: "compress",
    group: "compression",
    emoji: "🐚",
    wired: true,
    desc: "Fibonacci decomposition — every token finds optimal position in Golden Ratio structure.",
    claim: "QFAI-001: Fibonacci",
    file: "qfai-c",
  },
  {
    id: "qfai_steno",
    name: "Steganographic Embed",
    phase: "compress",
    group: "compression",
    emoji: "🪶",
    wired: true,
    desc: "Hides metadata within compressed output like invisible ink — preserving audit trail.",
    claim: "QFAI-002: Steno",
    file: "qfai-c",
  },
  {
    id: "qfai_phi",
    name: "φ-Weight Optimizer",
    phase: "compress",
    group: "compression",
    emoji: "🌻",
    wired: true,
    desc: "Weights tokens by semantic importance using Golden Ratio — most meaningful preserved first.",
    claim: "QFAI-003: φ-Weight",
    file: "qfai-c",
  },
  {
    id: "qfai_distill",
    name: "Semantic Distillation",
    phase: "compress",
    group: "compression",
    emoji: "🧪",
    wired: true,
    desc: "Extracts pure meaning from verbose prompts — like distilling essential oils from raw flowers.",
    claim: "QFAI-004: Distill",
    file: "qfai-c",
  },
  {
    id: "qfai_entropy",
    name: "Entropy Reducer",
    phase: "compress",
    group: "compression",
    emoji: "❄️",
    wired: true,
    desc: "Removes redundant information — cooling the prompt to minimum energy state.",
    claim: "QFAI-005: Entropy",
    file: "qfai-c",
  },
  {
    id: "qfai_recon",
    name: "Meaning Reconstructor",
    phase: "compress",
    group: "compression",
    emoji: "🧩",
    wired: true,
    desc: "Rebuilds full semantic context from compressed tokens — proves lossless meaning preservation.",
    claim: "QFAI-006: Reconstruct",
    file: "qfai-c",
  },
  {
    id: "qfai_wormhole",
    name: "LLM Wormhole Inject",
    phase: "compress",
    group: "compression",
    emoji: "🕳️",
    wired: true,
    desc: "Compressed prompt enters the LLM black hole — minimal tokens, maximum meaning.",
    claim: "LLM Injection Point",
    file: "qfai-c",
  },

  // ═══ PHASE 3: AUDIT (SIREN) ═══
  {
    id: "siren_genome",
    name: "Alignment Genome",
    phase: "audit",
    group: "siren",
    emoji: "🧬",
    wired: true,
    desc: 'Immutable 12D reference vector — the AI\'s DNA defining what "aligned" means.',
    claim: "AI-001: 12D Genome",
    file: "alignment-genome.ts",
  },
  {
    id: "siren_rav",
    name: "Resonance Alignment",
    phase: "audit",
    group: "siren",
    emoji: "🐬",
    wired: true,
    desc: "Dolphins echolocate distortions. SIREN checks if output resonates with Alignment Genome across 12 Heim dimensions.",
    claim: "AI-002: RAV",
    file: "siren/engine.ts",
  },
  {
    id: "siren_qiat",
    name: "QIAT Threshold",
    phase: "audit",
    group: "siren",
    emoji: "✨",
    wired: true,
    desc: "Quantum-shifted acceptance — true randomness from Cisco QRNG prevents predicting decision boundary.",
    claim: "AI-003: QIAT",
    file: "siren/engine.ts",
  },
  {
    id: "siren_drift",
    name: "Gradualist Drift",
    phase: "audit",
    group: "siren",
    emoji: "🌊",
    wired: true,
    desc: "Boiling frog detector — Mann-Kendall analysis over F(10)=55 window catches slow alignment drift.",
    claim: "AI-004: Drift",
    file: "siren/engine.ts",
  },
  {
    id: "siren_negentropy",
    name: "Negentropy Monitor",
    phase: "audit",
    group: "siren",
    emoji: "❤️",
    wired: true,
    desc: "AI vital signs — heartbeat monitor tracking system coherence. Green ≥φ⁻¹, Yellow, Red zones.",
    claim: "AI-005: Vitals",
    file: "siren/engine.ts",
  },
  {
    id: "siren_avr",
    name: "AVR Hash Chain",
    phase: "audit",
    group: "siren",
    emoji: "⛓️",
    wired: true,
    desc: "Every verification hash-chained into immutable audit trail. Anchored to Polygon every F(8)=21 records.",
    claim: "AI-006: Blockchain",
    file: "siren/engine.ts",
  },
  {
    id: "siren_feedback",
    name: "Scythe Feedback",
    phase: "audit",
    group: "siren",
    emoji: "🌙",
    wired: true,
    desc: "Inoculation loop — SIREN violations feed back to AEGIS PMB, permanently vaccinating against attack patterns.",
    claim: "Feedback → AEGIS",
    file: "siren-feedback-coordinator.ts",
  },
  {
    id: "heart",
    name: "Heart Coherence",
    phase: "audit",
    group: "siren",
    emoji: "💗",
    wired: true,
    desc: "Central pulse synchronizing all layers — like heart's 0.1Hz rhythm coordinating brain, breath, body.",
    claim: "Phase 3: Heart-Coherent AI",
    file: "ni/index.ts",
  },

  // ═══ UNWIRED / PLANNED (at 20% opacity) ═══
  {
    id: "dead_anticipatory",
    name: "Anticipatory Defense",
    phase: "shield",
    group: "intent",
    emoji: "\u{1F52E}",
    wired: false,
    desc: "PLANNED: Pre-emptive defense based on attack pattern prediction.",
    claim: "UNWIRED",
    file: "anticipatory-defense-detector.ts",
  },
  {
    id: "dead_code_exec",
    name: "Code Execution Det.",
    phase: "shield",
    group: "encoding",
    emoji: "\u{1F4BB}",
    wired: false,
    desc: "PLANNED: Detects code execution attempts embedded in prompts.",
    claim: "UNWIRED",
    file: "code-execution-detector.ts",
  },
  {
    id: "dead_composite",
    name: "Composite Anomaly",
    phase: "shield",
    group: "forensics",
    emoji: "\u{1F504}",
    wired: false,
    desc: "PLANNED: Multi-signal anomaly aggregator.",
    claim: "UNWIRED",
    file: "composite-anomaly-detector.ts",
  },
  {
    id: "dead_gricean",
    name: "Gricean Maxim",
    phase: "shield",
    group: "intent",
    emoji: "\u{1F5E3}\uFE0F",
    wired: false,
    desc: "PLANNED: Conversational pragmatics \u2014 detects violations of Grice's cooperative principles.",
    claim: "UNWIRED",
    file: "gricean-maxim-analyzer.ts",
  },
  {
    id: "dead_harmonic",
    name: "Harmonic Coherence",
    phase: "shield",
    group: "physics",
    emoji: "\u{1F3B6}",
    wired: false,
    desc: "PLANNED: \u03C6-harmonic analysis of token distribution patterns.",
    claim: "UNWIRED",
    file: "harmonic-coherence-gate.ts",
  },
  {
    id: "dead_holographic",
    name: "Holographic Interf.",
    phase: "shield",
    group: "physics",
    emoji: "\u{1F308}",
    wired: false,
    desc: "PLANNED: Multi-dimensional interference pattern detection.",
    claim: "UNWIRED",
    file: "holographic-interference-detector.ts",
  },
  {
    id: "dead_honest",
    name: "Honest Signal",
    phase: "shield",
    group: "biomimicry",
    emoji: "\u{1F99A}",
    wired: false,
    desc: "PLANNED: Biological honest signaling \u2014 costly signals that can't be faked.",
    claim: "UNWIRED",
    file: "honest-signal-detector.ts",
  },
  {
    id: "dead_meta",
    name: "Injection Meta-Det.",
    phase: "shield",
    group: "v2_cascade",
    emoji: "\u{1F441}\uFE0F",
    wired: false,
    desc: "PLANNED: Meta-analysis aggregator for all injection detectors.",
    claim: "UNWIRED",
    file: "prompt-injection-meta-detector.ts",
  },
  {
    id: "dead_storm",
    name: "Storm Warning",
    phase: "shield",
    group: "forensics",
    emoji: "\u{1F329}\uFE0F",
    wired: false,
    desc: "PLANNED: Multi-turn storm detection \u2014 long-horizon attack weather forecasting.",
    claim: "UNWIRED",
    file: "storm-warning-detector.ts",
  },
  {
    id: "dead_structural",
    name: "Structural Org.",
    phase: "shield",
    group: "twain",
    emoji: "\u{1F3D7}\uFE0F",
    wired: false,
    desc: "PLANNED: Structural prompt organization analysis.",
    claim: "UNWIRED",
    file: "structural-organization-detector.ts",
  },
  {
    id: "dead_tele_traj",
    name: "Teleological Traj.",
    phase: "shield",
    group: "waves",
    emoji: "\u2604\uFE0F",
    wired: false,
    desc: "PLANNED: Deep purpose trajectory analysis over conversation history.",
    claim: "UNWIRED",
    file: "teleological-trajectory-analyzer.ts",
  },
  {
    id: "dead_turbulence",
    name: "Turbulence Detector",
    phase: "shield",
    group: "physics",
    emoji: "\u{1F32A}\uFE0F",
    wired: false,
    desc: "PLANNED: Session turbulence measurement \u2014 rapid topic/style changes.",
    claim: "UNWIRED",
    file: "turbulence-detector.ts",
  },
  {
    id: "dead_ultrasonic",
    name: "Ultrasonic Verb Inv.",
    phase: "shield",
    group: "encoding",
    emoji: "\u{1F50A}",
    wired: false,
    desc: "PLANNED: Verb-level semantic inversion attack detection.",
    claim: "UNWIRED",
    file: "ultrasonic-verb-inversion.ts",
  },
  {
    id: "dead_rag",
    name: "RAG Screening",
    phase: "shield",
    group: "memory",
    emoji: "\u{1F4DA}",
    wired: false,
    desc: "PLANNED: RAG-specific injection screening for retrieval-augmented generation.",
    claim: "UNWIRED",
    file: "rag-screening.ts",
  },
  {
    id: "dead_jurisdiction",
    name: "Jurisdictional Shield",
    phase: "shield",
    group: "constitutional",
    emoji: "\u{1F5FA}\uFE0F",
    wired: false,
    desc: "PLANNED: Geo-legal compliance layer \u2014 adapts defenses to jurisdiction (EU/US/APAC).",
    claim: "UNWIRED",
    file: "jurisdictional-shield.ts",
  },
];

// Convenience counters
var WIRED_COUNT = ALL_LAYERS.filter(function (l) {
  return l.wired;
}).length;
var DEAD_COUNT = ALL_LAYERS.filter(function (l) {
  return !l.wired;
}).length;
var TOTAL_COUNT = ALL_LAYERS.length;
var GROUP_COUNTS = {};
ALL_LAYERS.forEach(function (l) {
  if (!GROUP_COUNTS[l.group]) GROUP_COUNTS[l.group] = 0;
  GROUP_COUNTS[l.group]++;
  // Auto-assign role from SSOT ROLE_MAP
  l.role = ROLE_MAP[l.id] || "blocker";
});
var ROLE_COUNTS = {};
ALL_LAYERS.forEach(function (l) {
  if (!ROLE_COUNTS[l.role]) ROLE_COUNTS[l.role] = 0;
  ROLE_COUNTS[l.role]++;
});
